spring:
  application:
    name: MoveCloud-Login-Service
  datasource:
    url: jdbc:mysql://localhost:3306/movecloud
    username: root
    password: dushyanth
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8084
  servlet:
    session:
      cookie:
        same-site: strict

logging:
  level:
    org:
      springframework:
        security: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/