name: CI/CD Pipeline

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build with Maven
      run: mvn clean package

    - name: Build docker image
      run: docker build -t login-service .

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Tag Docker Image
      run: docker tag login-service:latest ${{ secrets.DOCKERHUB_USERNAME }}/login-service:latest

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/login-service:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

#      - name: Ping the address
#        run: ping ${{ secrets.SERVER_HOST }}

      - name: SSH into Server and Deploy Docker
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no "${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}" << 'EOF'
            docker pull siddarthpaladi/login-service:latest
            docker stop login-service || true
            docker rm login-service || true
            docker run -d --name login-service -p 8080:8080 siddarthpaladi/login-service:latest
          EOF
